SELECT 
    COUNT(*) AS FISH_COUNT,
    MAX(COALESCE(FI.LENGTH, 10)) AS MAX_LENGTH,
    FI.FISH_TYPE
FROM FISH_INFO FI
GROUP BY FI.FISH_TYPE
HAVING AVG(COALESCE(FI.LENGTH, 10)) >= 33
ORDER BY FI.FISH_TYPE;

-- HAVING : 그룹 단위로 조건 설정 (그룹화 이후 조건, WHERE : 그룹화 전 조건)
-- 논리적 실행 순서 : FROM -> WHERE -> GROUP BY -> 집계 함수 계산 (COUNT, MAX) -> HAVING -> SELECT -> ORDER BY -> LIMIT